In [1]:
import pandas as pd

In [2]:
data=pd.read_csv("employees.csv")
data

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,198,Donald,OConnell,DOCONNEL,650.507.9833,21-JUN-07,SH_CLERK,2600,-,124,50
1,199,Douglas,Grant,DGRANT,650.507.9844,13-JAN-08,SH_CLERK,2600,-,124,50
2,200,Jennifer,Whalen,JWHALEN,515.123.4444,17-SEP-03,AD_ASST,4400,-,101,10
3,201,Michael,Hartstein,MHARTSTE,515.123.5555,17-FEB-04,MK_MAN,13000,-,100,20
4,202,Pat,Fay,PFAY,603.123.6666,17-AUG-05,MK_REP,6000,-,201,20
5,203,Susan,Mavris,SMAVRIS,515.123.7777,07-JUN-02,HR_REP,6500,-,101,40
6,204,Hermann,Baer,HBAER,515.123.8888,07-JUN-02,PR_REP,10000,-,101,70
7,205,Shelley,Higgins,SHIGGINS,515.123.8080,07-JUN-02,AC_MGR,12008,-,101,110
8,206,William,Gietz,WGIETZ,515.123.8181,07-JUN-02,AC_ACCOUNT,8300,-,205,110
9,100,Steven,King,SKING,515.123.4567,17-JUN-03,AD_PRES,24000,-,-,90
10,101,Neena,Kochhar,NKOCHHAR,515.123.4568,21-SEP-05,AD_VP,17000,-,100,90
11,102,Lex,De Haan,LDEHAAN,515.123.4569,13-JAN-01,AD_VP,17000,-,100,90
12,103,Alexander,Hunold,AHUNOLD,590.423.4567,03-JAN-06,IT_PROG,9000,-,102,60
13,104,Bruce,Ernst,BERNST,590.423.4568,21-MAY-07,IT_PROG,6000,-,103,60
14,105,David,Austin,DAUSTIN,590.423.4569,25-JUN-05,IT_PROG,4800,-,103,60
15,106,Valli,Pataballa,VPATABAL,590.423.4560,05-FEB-06,IT_PROG,4800,-,103,60
16,107,Diana,Lorentz,DLORENTZ,590.423.5567,07-FEB-07,IT_PROG,4200,-,103,60
17,108,Nancy,Greenberg,NGREENBE,515.124.4569,17-AUG-02,FI_MGR,12008,-,101,100
18,109,Daniel,Faviet,DFAVIET,515.124.4169,16-AUG-02,FI_ACCOUNT,9000,-,108,100
19,110,John,Chen,JCHEN,515.124.4269,28-SEP-05,FI_ACCOUNT,8200,-,108,100
20,111,Ismael,Sciarra,ISCIARRA,515.124.4369,30-SEP-05,FI_ACCOUNT,7700,-,108,100
21,112,Jose Manuel,Urman,JMURMAN,515.124.4469,07-MAR-06,FI_ACCOUNT,7800,-,108,100
22,113,Luis,Popp,LPOPP,515.124.4567,07-DEC-07,FI_ACCOUNT,6900,-,108,100
23,114,Den,Raphaely,DRAPHEAL,515.127.4561,07-DEC-02,PU_MAN,11000,-,100,30
24,115,Alexander,Khoo,AKHOO,515.127.4562,18-MAY-03,PU_CLERK,3100,-,114,30
25,116,Shelli,Baida,SBAIDA,515.127.4563,24-DEC-05,PU_CLERK,2900,-,114,30
26,117,Sigal,Tobias,STOBIAS,515.127.4564,24-JUL-05,PU_CLERK,2800,-,114,30
27,118,Guy,Himuro,GHIMURO,515.127.4565,15-NOV-06,PU_CLERK,2600,-,114,30
28,119,Karen,Colmenares,KCOLMENA,515.127.4566,10-AUG-07,PU_CLERK,2500,-,114,30
29,120,Matthew,Weiss,MWEISS,650.123.1234,18-JUL-04,ST_MAN,8000,-,100,50
30,121,Adam,Fripp,AFRIPP,650.123.2234,10-APR-05,ST_MAN,8200,-,100,50
31,122,Payam,Kaufling,PKAUFLIN,650.123.3234,01-MAY-03,ST_MAN,7900,-,100,50
32,123,Shanta,Vollman,SVOLLMAN,650.123.4234,10-OCT-05,ST_MAN,6500,-,100,50
33,124,Kevin,Mourgos,KMOURGOS,650.123.5234,16-NOV-07,ST_MAN,5800,-,100,50
34,125,Julia,Nayer,JNAYER,650.124.1214,16-JUL-05,ST_CLERK,3200,-,120,50
35,126,Irene,Mikkilineni,IMIKKILI,650.124.1224,28-SEP-06,ST_CLERK,2700,-,120,50
36,127,James,Landry,JLANDRY,650.124.1334,14-JAN-07,ST_CLERK,2400,-,120,50
37,128,Steven,Markle,SMARKLE,650.124.1434,08-MAR-08,ST_CLERK,2200,-,120,50
38,129,Laura,Bissot,LBISSOT,650.124.5234,20-AUG-05,ST_CLERK,3300,-,121,50
39,130,Mozhe,Atkinson,MATKINSO,650.124.6234,30-OCT-05,ST_CLERK,2800,-,121,50
40,131,James,Marlow,JAMRLOW,650.124.7234,16-FEB-05,ST_CLERK,2500,-,121,50
41,132,TJ,Olson,TJOLSON,650.124.8234,10-APR-07,ST_CLERK,2100,-,121,50
42,133,Jason,Mallin,JMALLIN,650.127.1934,14-JUN-04,ST_CLERK,3300,-,122,50
43,134,Michael,Rogers,MROGERS,650.127.1834,26-AUG-06,ST_CLERK,2900,-,122,50
44,135,Ki,Gee,KGEE,650.127.1734,12-DEC-07,ST_CLERK,2400,-,122,50
45,136,Hazel,Philtanker,HPHILTAN,650.127.1634,06-FEB-08,ST_CLERK,2200,-,122,50
46,137,Renske,Ladwig,RLADWIG,650.121.1234,14-JUL-03,ST_CLERK,3600,-,123,50
47,138,Stephen,Stiles,SSTILES,650.121.2034,26-OCT-05,ST_CLERK,3200,-,123,50
48,139,John,Seo,JSEO,650.121.2019,12-FEB-06,ST_CLERK,2700,-,123,50
49,140,Joshua,Patel,JPATEL,650.121.1834,06-APR-06,ST_CLERK,2500,-,123,50

In [3]:
salary=data['SALARY']

In [4]:
salary

0      2600
1      2600
2      4400
3     13000
4      6000
5      6500
6     10000
7     12008
8      8300
9     24000
10    17000
11    17000
12     9000
13     6000
14     4800
15     4800
16     4200
17    12008
18     9000
19     8200
20     7700
21     7800
22     6900
23    11000
24     3100
25     2900
26     2800
27     2600
28     2500
29     8000
30     8200
31     7900
32     6500
33     5800
34     3200
35     2700
36     2400
37     2200
38     3300
39     2800
40     2500
41     2100
42     3300
43     2900
44     2400
45     2200
46     3600
47     3200
48     2700
49     2500
Name: SALARY, dtype: int64

In [5]:
data.fillna(0,inplace=True)
data

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,198,Donald,OConnell,DOCONNEL,650.507.9833,21-JUN-07,SH_CLERK,2600,-,124,50
1,199,Douglas,Grant,DGRANT,650.507.9844,13-JAN-08,SH_CLERK,2600,-,124,50
2,200,Jennifer,Whalen,JWHALEN,515.123.4444,17-SEP-03,AD_ASST,4400,-,101,10
3,201,Michael,Hartstein,MHARTSTE,515.123.5555,17-FEB-04,MK_MAN,13000,-,100,20
4,202,Pat,Fay,PFAY,603.123.6666,17-AUG-05,MK_REP,6000,-,201,20
5,203,Susan,Mavris,SMAVRIS,515.123.7777,07-JUN-02,HR_REP,6500,-,101,40
6,204,Hermann,Baer,HBAER,515.123.8888,07-JUN-02,PR_REP,10000,-,101,70
7,205,Shelley,Higgins,SHIGGINS,515.123.8080,07-JUN-02,AC_MGR,12008,-,101,110
8,206,William,Gietz,WGIETZ,515.123.8181,07-JUN-02,AC_ACCOUNT,8300,-,205,110
9,100,Steven,King,SKING,515.123.4567,17-JUN-03,AD_PRES,24000,-,-,90
10,101,Neena,Kochhar,NKOCHHAR,515.123.4568,21-SEP-05,AD_VP,17000,-,100,90
11,102,Lex,De Haan,LDEHAAN,515.123.4569,13-JAN-01,AD_VP,17000,-,100,90
12,103,Alexander,Hunold,AHUNOLD,590.423.4567,03-JAN-06,IT_PROG,9000,-,102,60
13,104,Bruce,Ernst,BERNST,590.423.4568,21-MAY-07,IT_PROG,6000,-,103,60
14,105,David,Austin,DAUSTIN,590.423.4569,25-JUN-05,IT_PROG,4800,-,103,60
15,106,Valli,Pataballa,VPATABAL,590.423.4560,05-FEB-06,IT_PROG,4800,-,103,60
16,107,Diana,Lorentz,DLORENTZ,590.423.5567,07-FEB-07,IT_PROG,4200,-,103,60
17,108,Nancy,Greenberg,NGREENBE,515.124.4569,17-AUG-02,FI_MGR,12008,-,101,100
18,109,Daniel,Faviet,DFAVIET,515.124.4169,16-AUG-02,FI_ACCOUNT,9000,-,108,100
19,110,John,Chen,JCHEN,515.124.4269,28-SEP-05,FI_ACCOUNT,8200,-,108,100
20,111,Ismael,Sciarra,ISCIARRA,515.124.4369,30-SEP-05,FI_ACCOUNT,7700,-,108,100
21,112,Jose Manuel,Urman,JMURMAN,515.124.4469,07-MAR-06,FI_ACCOUNT,7800,-,108,100
22,113,Luis,Popp,LPOPP,515.124.4567,07-DEC-07,FI_ACCOUNT,6900,-,108,100
23,114,Den,Raphaely,DRAPHEAL,515.127.4561,07-DEC-02,PU_MAN,11000,-,100,30
24,115,Alexander,Khoo,AKHOO,515.127.4562,18-MAY-03,PU_CLERK,3100,-,114,30
25,116,Shelli,Baida,SBAIDA,515.127.4563,24-DEC-05,PU_CLERK,2900,-,114,30
26,117,Sigal,Tobias,STOBIAS,515.127.4564,24-JUL-05,PU_CLERK,2800,-,114,30
27,118,Guy,Himuro,GHIMURO,515.127.4565,15-NOV-06,PU_CLERK,2600,-,114,30
28,119,Karen,Colmenares,KCOLMENA,515.127.4566,10-AUG-07,PU_CLERK,2500,-,114,30
29,120,Matthew,Weiss,MWEISS,650.123.1234,18-JUL-04,ST_MAN,8000,-,100,50
30,121,Adam,Fripp,AFRIPP,650.123.2234,10-APR-05,ST_MAN,8200,-,100,50
31,122,Payam,Kaufling,PKAUFLIN,650.123.3234,01-MAY-03,ST_MAN,7900,-,100,50
32,123,Shanta,Vollman,SVOLLMAN,650.123.4234,10-OCT-05,ST_MAN,6500,-,100,50
33,124,Kevin,Mourgos,KMOURGOS,650.123.5234,16-NOV-07,ST_MAN,5800,-,100,50
34,125,Julia,Nayer,JNAYER,650.124.1214,16-JUL-05,ST_CLERK,3200,-,120,50
35,126,Irene,Mikkilineni,IMIKKILI,650.124.1224,28-SEP-06,ST_CLERK,2700,-,120,50
36,127,James,Landry,JLANDRY,650.124.1334,14-JAN-07,ST_CLERK,2400,-,120,50
37,128,Steven,Markle,SMARKLE,650.124.1434,08-MAR-08,ST_CLERK,2200,-,120,50
38,129,Laura,Bissot,LBISSOT,650.124.5234,20-AUG-05,ST_CLERK,3300,-,121,50
39,130,Mozhe,Atkinson,MATKINSO,650.124.6234,30-OCT-05,ST_CLERK,2800,-,121,50
40,131,James,Marlow,JAMRLOW,650.124.7234,16-FEB-05,ST_CLERK,2500,-,121,50
41,132,TJ,Olson,TJOLSON,650.124.8234,10-APR-07,ST_CLERK,2100,-,121,50
42,133,Jason,Mallin,JMALLIN,650.127.1934,14-JUN-04,ST_CLERK,3300,-,122,50
43,134,Michael,Rogers,MROGERS,650.127.1834,26-AUG-06,ST_CLERK,2900,-,122,50
44,135,Ki,Gee,KGEE,650.127.1734,12-DEC-07,ST_CLERK,2400,-,122,50
45,136,Hazel,Philtanker,HPHILTAN,650.127.1634,06-FEB-08,ST_CLERK,2200,-,122,50
46,137,Renske,Ladwig,RLADWIG,650.121.1234,14-JUL-03,ST_CLERK,3600,-,123,50
47,138,Stephen,Stiles,SSTILES,650.121.2034,26-OCT-05,ST_CLERK,3200,-,123,50
48,139,John,Seo,JSEO,650.121.2019,12-FEB-06,ST_CLERK,2700,-,123,50
49,140,Joshua,Patel,JPATEL,650.121.1834,06-APR-06,ST_CLERK,2500,-,123,50

In [8]:
data["COMMISSION_PCT"]=data["COMMISSION_PCT"].replace("-","0")
data

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,198,Donald,OConnell,DOCONNEL,650.507.9833,21-JUN-07,SH_CLERK,2600,-,124,50
1,199,Douglas,Grant,DGRANT,650.507.9844,13-JAN-08,SH_CLERK,2600,-,124,50
2,200,Jennifer,Whalen,JWHALEN,515.123.4444,17-SEP-03,AD_ASST,4400,-,101,10
3,201,Michael,Hartstein,MHARTSTE,515.123.5555,17-FEB-04,MK_MAN,13000,-,100,20
4,202,Pat,Fay,PFAY,603.123.6666,17-AUG-05,MK_REP,6000,-,201,20
5,203,Susan,Mavris,SMAVRIS,515.123.7777,07-JUN-02,HR_REP,6500,-,101,40
6,204,Hermann,Baer,HBAER,515.123.8888,07-JUN-02,PR_REP,10000,-,101,70
7,205,Shelley,Higgins,SHIGGINS,515.123.8080,07-JUN-02,AC_MGR,12008,-,101,110
8,206,William,Gietz,WGIETZ,515.123.8181,07-JUN-02,AC_ACCOUNT,8300,-,205,110
9,100,Steven,King,SKING,515.123.4567,17-JUN-03,AD_PRES,24000,-,-,90
10,101,Neena,Kochhar,NKOCHHAR,515.123.4568,21-SEP-05,AD_VP,17000,-,100,90
11,102,Lex,De Haan,LDEHAAN,515.123.4569,13-JAN-01,AD_VP,17000,-,100,90
12,103,Alexander,Hunold,AHUNOLD,590.423.4567,03-JAN-06,IT_PROG,9000,-,102,60
13,104,Bruce,Ernst,BERNST,590.423.4568,21-MAY-07,IT_PROG,6000,-,103,60
14,105,David,Austin,DAUSTIN,590.423.4569,25-JUN-05,IT_PROG,4800,-,103,60
15,106,Valli,Pataballa,VPATABAL,590.423.4560,05-FEB-06,IT_PROG,4800,-,103,60
16,107,Diana,Lorentz,DLORENTZ,590.423.5567,07-FEB-07,IT_PROG,4200,-,103,60
17,108,Nancy,Greenberg,NGREENBE,515.124.4569,17-AUG-02,FI_MGR,12008,-,101,100
18,109,Daniel,Faviet,DFAVIET,515.124.4169,16-AUG-02,FI_ACCOUNT,9000,-,108,100
19,110,John,Chen,JCHEN,515.124.4269,28-SEP-05,FI_ACCOUNT,8200,-,108,100
20,111,Ismael,Sciarra,ISCIARRA,515.124.4369,30-SEP-05,FI_ACCOUNT,7700,-,108,100
21,112,Jose Manuel,Urman,JMURMAN,515.124.4469,07-MAR-06,FI_ACCOUNT,7800,-,108,100
22,113,Luis,Popp,LPOPP,515.124.4567,07-DEC-07,FI_ACCOUNT,6900,-,108,100
23,114,Den,Raphaely,DRAPHEAL,515.127.4561,07-DEC-02,PU_MAN,11000,-,100,30
24,115,Alexander,Khoo,AKHOO,515.127.4562,18-MAY-03,PU_CLERK,3100,-,114,30
25,116,Shelli,Baida,SBAIDA,515.127.4563,24-DEC-05,PU_CLERK,2900,-,114,30
26,117,Sigal,Tobias,STOBIAS,515.127.4564,24-JUL-05,PU_CLERK,2800,-,114,30
27,118,Guy,Himuro,GHIMURO,515.127.4565,15-NOV-06,PU_CLERK,2600,-,114,30
28,119,Karen,Colmenares,KCOLMENA,515.127.4566,10-AUG-07,PU_CLERK,2500,-,114,30
29,120,Matthew,Weiss,MWEISS,650.123.1234,18-JUL-04,ST_MAN,8000,-,100,50
30,121,Adam,Fripp,AFRIPP,650.123.2234,10-APR-05,ST_MAN,8200,-,100,50
31,122,Payam,Kaufling,PKAUFLIN,650.123.3234,01-MAY-03,ST_MAN,7900,-,100,50
32,123,Shanta,Vollman,SVOLLMAN,650.123.4234,10-OCT-05,ST_MAN,6500,-,100,50
33,124,Kevin,Mourgos,KMOURGOS,650.123.5234,16-NOV-07,ST_MAN,5800,-,100,50
34,125,Julia,Nayer,JNAYER,650.124.1214,16-JUL-05,ST_CLERK,3200,-,120,50
35,126,Irene,Mikkilineni,IMIKKILI,650.124.1224,28-SEP-06,ST_CLERK,2700,-,120,50
36,127,James,Landry,JLANDRY,650.124.1334,14-JAN-07,ST_CLERK,2400,-,120,50
37,128,Steven,Markle,SMARKLE,650.124.1434,08-MAR-08,ST_CLERK,2200,-,120,50
38,129,Laura,Bissot,LBISSOT,650.124.5234,20-AUG-05,ST_CLERK,3300,-,121,50
39,130,Mozhe,Atkinson,MATKINSO,650.124.6234,30-OCT-05,ST_CLERK,2800,-,121,50
40,131,James,Marlow,JAMRLOW,650.124.7234,16-FEB-05,ST_CLERK,2500,-,121,50
41,132,TJ,Olson,TJOLSON,650.124.8234,10-APR-07,ST_CLERK,2100,-,121,50
42,133,Jason,Mallin,JMALLIN,650.127.1934,14-JUN-04,ST_CLERK,3300,-,122,50
43,134,Michael,Rogers,MROGERS,650.127.1834,26-AUG-06,ST_CLERK,2900,-,122,50
44,135,Ki,Gee,KGEE,650.127.1734,12-DEC-07,ST_CLERK,2400,-,122,50
45,136,Hazel,Philtanker,HPHILTAN,650.127.1634,06-FEB-08,ST_CLERK,2200,-,122,50
46,137,Renske,Ladwig,RLADWIG,650.121.1234,14-JUL-03,ST_CLERK,3600,-,123,50
47,138,Stephen,Stiles,SSTILES,650.121.2034,26-OCT-05,ST_CLERK,3200,-,123,50
48,139,John,Seo,JSEO,650.121.2019,12-FEB-06,ST_CLERK,2700,-,123,50
49,140,Joshua,Patel,JPATEL,650.121.1834,06-APR-06,ST_CLERK,2500,-,123,50

In [7]:
data

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,198,Donald,OConnell,DOCONNEL,650.507.9833,21-JUN-07,SH_CLERK,2600,-,124,50
1,199,Douglas,Grant,DGRANT,650.507.9844,13-JAN-08,SH_CLERK,2600,-,124,50
2,200,Jennifer,Whalen,JWHALEN,515.123.4444,17-SEP-03,AD_ASST,4400,-,101,10
3,201,Michael,Hartstein,MHARTSTE,515.123.5555,17-FEB-04,MK_MAN,13000,-,100,20
4,202,Pat,Fay,PFAY,603.123.6666,17-AUG-05,MK_REP,6000,-,201,20
5,203,Susan,Mavris,SMAVRIS,515.123.7777,07-JUN-02,HR_REP,6500,-,101,40
6,204,Hermann,Baer,HBAER,515.123.8888,07-JUN-02,PR_REP,10000,-,101,70
7,205,Shelley,Higgins,SHIGGINS,515.123.8080,07-JUN-02,AC_MGR,12008,-,101,110
8,206,William,Gietz,WGIETZ,515.123.8181,07-JUN-02,AC_ACCOUNT,8300,-,205,110
9,100,Steven,King,SKING,515.123.4567,17-JUN-03,AD_PRES,24000,-,-,90
10,101,Neena,Kochhar,NKOCHHAR,515.123.4568,21-SEP-05,AD_VP,17000,-,100,90
11,102,Lex,De Haan,LDEHAAN,515.123.4569,13-JAN-01,AD_VP,17000,-,100,90
12,103,Alexander,Hunold,AHUNOLD,590.423.4567,03-JAN-06,IT_PROG,9000,-,102,60
13,104,Bruce,Ernst,BERNST,590.423.4568,21-MAY-07,IT_PROG,6000,-,103,60
14,105,David,Austin,DAUSTIN,590.423.4569,25-JUN-05,IT_PROG,4800,-,103,60
15,106,Valli,Pataballa,VPATABAL,590.423.4560,05-FEB-06,IT_PROG,4800,-,103,60
16,107,Diana,Lorentz,DLORENTZ,590.423.5567,07-FEB-07,IT_PROG,4200,-,103,60
17,108,Nancy,Greenberg,NGREENBE,515.124.4569,17-AUG-02,FI_MGR,12008,-,101,100
18,109,Daniel,Faviet,DFAVIET,515.124.4169,16-AUG-02,FI_ACCOUNT,9000,-,108,100
19,110,John,Chen,JCHEN,515.124.4269,28-SEP-05,FI_ACCOUNT,8200,-,108,100
20,111,Ismael,Sciarra,ISCIARRA,515.124.4369,30-SEP-05,FI_ACCOUNT,7700,-,108,100
21,112,Jose Manuel,Urman,JMURMAN,515.124.4469,07-MAR-06,FI_ACCOUNT,7800,-,108,100
22,113,Luis,Popp,LPOPP,515.124.4567,07-DEC-07,FI_ACCOUNT,6900,-,108,100
23,114,Den,Raphaely,DRAPHEAL,515.127.4561,07-DEC-02,PU_MAN,11000,-,100,30
24,115,Alexander,Khoo,AKHOO,515.127.4562,18-MAY-03,PU_CLERK,3100,-,114,30
25,116,Shelli,Baida,SBAIDA,515.127.4563,24-DEC-05,PU_CLERK,2900,-,114,30
26,117,Sigal,Tobias,STOBIAS,515.127.4564,24-JUL-05,PU_CLERK,2800,-,114,30
27,118,Guy,Himuro,GHIMURO,515.127.4565,15-NOV-06,PU_CLERK,2600,-,114,30
28,119,Karen,Colmenares,KCOLMENA,515.127.4566,10-AUG-07,PU_CLERK,2500,-,114,30
29,120,Matthew,Weiss,MWEISS,650.123.1234,18-JUL-04,ST_MAN,8000,-,100,50
30,121,Adam,Fripp,AFRIPP,650.123.2234,10-APR-05,ST_MAN,8200,-,100,50
31,122,Payam,Kaufling,PKAUFLIN,650.123.3234,01-MAY-03,ST_MAN,7900,-,100,50
32,123,Shanta,Vollman,SVOLLMAN,650.123.4234,10-OCT-05,ST_MAN,6500,-,100,50
33,124,Kevin,Mourgos,KMOURGOS,650.123.5234,16-NOV-07,ST_MAN,5800,-,100,50
34,125,Julia,Nayer,JNAYER,650.124.1214,16-JUL-05,ST_CLERK,3200,-,120,50
35,126,Irene,Mikkilineni,IMIKKILI,650.124.1224,28-SEP-06,ST_CLERK,2700,-,120,50
36,127,James,Landry,JLANDRY,650.124.1334,14-JAN-07,ST_CLERK,2400,-,120,50
37,128,Steven,Markle,SMARKLE,650.124.1434,08-MAR-08,ST_CLERK,2200,-,120,50
38,129,Laura,Bissot,LBISSOT,650.124.5234,20-AUG-05,ST_CLERK,3300,-,121,50
39,130,Mozhe,Atkinson,MATKINSO,650.124.6234,30-OCT-05,ST_CLERK,2800,-,121,50
40,131,James,Marlow,JAMRLOW,650.124.7234,16-FEB-05,ST_CLERK,2500,-,121,50
41,132,TJ,Olson,TJOLSON,650.124.8234,10-APR-07,ST_CLERK,2100,-,121,50
42,133,Jason,Mallin,JMALLIN,650.127.1934,14-JUN-04,ST_CLERK,3300,-,122,50
43,134,Michael,Rogers,MROGERS,650.127.1834,26-AUG-06,ST_CLERK,2900,-,122,50
44,135,Ki,Gee,KGEE,650.127.1734,12-DEC-07,ST_CLERK,2400,-,122,50
45,136,Hazel,Philtanker,HPHILTAN,650.127.1634,06-FEB-08,ST_CLERK,2200,-,122,50
46,137,Renske,Ladwig,RLADWIG,650.121.1234,14-JUL-03,ST_CLERK,3600,-,123,50
47,138,Stephen,Stiles,SSTILES,650.121.2034,26-OCT-05,ST_CLERK,3200,-,123,50
48,139,John,Seo,JSEO,650.121.2019,12-FEB-06,ST_CLERK,2700,-,123,50
49,140,Joshua,Patel,JPATEL,650.121.1834,06-APR-06,ST_CLERK,2500,-,123,50

In [9]:
min_max=(salary-salary.min())/(salary.max()-salary.min())
min_max

0     0.022831
1     0.022831
2     0.105023
3     0.497717
4     0.178082
5     0.200913
6     0.360731
7     0.452420
8     0.283105
9     1.000000
10    0.680365
11    0.680365
12    0.315068
13    0.178082
14    0.123288
15    0.123288
16    0.095890
17    0.452420
18    0.315068
19    0.278539
20    0.255708
21    0.260274
22    0.219178
23    0.406393
24    0.045662
25    0.036530
26    0.031963
27    0.022831
28    0.018265
29    0.269406
30    0.278539
31    0.264840
32    0.200913
33    0.168950
34    0.050228
35    0.027397
36    0.013699
37    0.004566
38    0.054795
39    0.031963
40    0.018265
41    0.000000
42    0.054795
43    0.036530
44    0.013699
45    0.004566
46    0.068493
47    0.050228
48    0.027397
49    0.018265
Name: SALARY, dtype: float64

In [10]:
data["SALARY"]=min_max
data

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,198,Donald,OConnell,DOCONNEL,650.507.9833,21-JUN-07,SH_CLERK,0.022831,-,124,50
1,199,Douglas,Grant,DGRANT,650.507.9844,13-JAN-08,SH_CLERK,0.022831,-,124,50
2,200,Jennifer,Whalen,JWHALEN,515.123.4444,17-SEP-03,AD_ASST,0.105023,-,101,10
3,201,Michael,Hartstein,MHARTSTE,515.123.5555,17-FEB-04,MK_MAN,0.497717,-,100,20
4,202,Pat,Fay,PFAY,603.123.6666,17-AUG-05,MK_REP,0.178082,-,201,20
5,203,Susan,Mavris,SMAVRIS,515.123.7777,07-JUN-02,HR_REP,0.200913,-,101,40
6,204,Hermann,Baer,HBAER,515.123.8888,07-JUN-02,PR_REP,0.360731,-,101,70
7,205,Shelley,Higgins,SHIGGINS,515.123.8080,07-JUN-02,AC_MGR,0.452420,-,101,110
8,206,William,Gietz,WGIETZ,515.123.8181,07-JUN-02,AC_ACCOUNT,0.283105,-,205,110
9,100,Steven,King,SKING,515.123.4567,17-JUN-03,AD_PRES,1.000000,-,-,90
10,101,Neena,Kochhar,NKOCHHAR,515.123.4568,21-SEP-05,AD_VP,0.680365,-,100,90
11,102,Lex,De Haan,LDEHAAN,515.123.4569,13-JAN-01,AD_VP,0.680365,-,100,90
12,103,Alexander,Hunold,AHUNOLD,590.423.4567,03-JAN-06,IT_PROG,0.315068,-,102,60
13,104,Bruce,Ernst,BERNST,590.423.4568,21-MAY-07,IT_PROG,0.178082,-,103,60
14,105,David,Austin,DAUSTIN,590.423.4569,25-JUN-05,IT_PROG,0.123288,-,103,60
15,106,Valli,Pataballa,VPATABAL,590.423.4560,05-FEB-06,IT_PROG,0.123288,-,103,60
16,107,Diana,Lorentz,DLORENTZ,590.423.5567,07-FEB-07,IT_PROG,0.095890,-,103,60
17,108,Nancy,Greenberg,NGREENBE,515.124.4569,17-AUG-02,FI_MGR,0.452420,-,101,100
18,109,Daniel,Faviet,DFAVIET,515.124.4169,16-AUG-02,FI_ACCOUNT,0.315068,-,108,100
19,110,John,Chen,JCHEN,515.124.4269,28-SEP-05,FI_ACCOUNT,0.278539,-,108,100
20,111,Ismael,Sciarra,ISCIARRA,515.124.4369,30-SEP-05,FI_ACCOUNT,0.255708,-,108,100
21,112,Jose Manuel,Urman,JMURMAN,515.124.4469,07-MAR-06,FI_ACCOUNT,0.260274,-,108,100
22,113,Luis,Popp,LPOPP,515.124.4567,07-DEC-07,FI_ACCOUNT,0.219178,-,108,100
23,114,Den,Raphaely,DRAPHEAL,515.127.4561,07-DEC-02,PU_MAN,0.406393,-,100,30
24,115,Alexander,Khoo,AKHOO,515.127.4562,18-MAY-03,PU_CLERK,0.045662,-,114,30
25,116,Shelli,Baida,SBAIDA,515.127.4563,24-DEC-05,PU_CLERK,0.036530,-,114,30
26,117,Sigal,Tobias,STOBIAS,515.127.4564,24-JUL-05,PU_CLERK,0.031963,-,114,30
27,118,Guy,Himuro,GHIMURO,515.127.4565,15-NOV-06,PU_CLERK,0.022831,-,114,30
28,119,Karen,Colmenares,KCOLMENA,515.127.4566,10-AUG-07,PU_CLERK,0.018265,-,114,30
29,120,Matthew,Weiss,MWEISS,650.123.1234,18-JUL-04,ST_MAN,0.269406,-,100,50
30,121,Adam,Fripp,AFRIPP,650.123.2234,10-APR-05,ST_MAN,0.278539,-,100,50
31,122,Payam,Kaufling,PKAUFLIN,650.123.3234,01-MAY-03,ST_MAN,0.264840,-,100,50
32,123,Shanta,Vollman,SVOLLMAN,650.123.4234,10-OCT-05,ST_MAN,0.200913,-,100,50
33,124,Kevin,Mourgos,KMOURGOS,650.123.5234,16-NOV-07,ST_MAN,0.168950,-,100,50
34,125,Julia,Nayer,JNAYER,650.124.1214,16-JUL-05,ST_CLERK,0.050228,-,120,50
35,126,Irene,Mikkilineni,IMIKKILI,650.124.1224,28-SEP-06,ST_CLERK,0.027397,-,120,50
36,127,James,Landry,JLANDRY,650.124.1334,14-JAN-07,ST_CLERK,0.013699,-,120,50
37,128,Steven,Markle,SMARKLE,650.124.1434,08-MAR-08,ST_CLERK,0.004566,-,120,50
38,129,Laura,Bissot,LBISSOT,650.124.5234,20-AUG-05,ST_CLERK,0.054795,-,121,50
39,130,Mozhe,Atkinson,MATKINSO,650.124.6234,30-OCT-05,ST_CLERK,0.031963,-,121,50
40,131,James,Marlow,JAMRLOW,650.124.7234,16-FEB-05,ST_CLERK,0.018265,-,121,50
41,132,TJ,Olson,TJOLSON,650.124.8234,10-APR-07,ST_CLERK,0.000000,-,121,50
42,133,Jason,Mallin,JMALLIN,650.127.1934,14-JUN-04,ST_CLERK,0.054795,-,122,50
43,134,Michael,Rogers,MROGERS,650.127.1834,26-AUG-06,ST_CLERK,0.036530,-,122,50
44,135,Ki,Gee,KGEE,650.127.1734,12-DEC-07,ST_CLERK,0.013699,-,122,50
45,136,Hazel,Philtanker,HPHILTAN,650.127.1634,06-FEB-08,ST_CLERK,0.004566,-,122,50
46,137,Renske,Ladwig,RLADWIG,650.121.1234,14-JUL-03,ST_CLERK,0.068493,-,123,50
47,138,Stephen,Stiles,SSTILES,650.121.2034,26-OCT-05,ST_CLERK,0.050228,-,123,50
48,139,John,Seo,JSEO,650.121.2019,12-FEB-06,ST_CLERK,0.027397,-,123,50
49,140,Joshua,Patel,JPATEL,650.121.1834,06-APR-06,ST_CLERK,0.018265,-,123,50

In [14]:
data["SALARY"]=salary
data
sal=(salary-salary.mean())/salary.std()
data["SALARY"]=sal
data

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,198,Donald,OConnell,DOCONNEL,650.507.9833,21-JUN-07,SH_CLERK,-0.781112,-,124,50
1,199,Douglas,Grant,DGRANT,650.507.9844,13-JAN-08,SH_CLERK,-0.781112,-,124,50
2,200,Jennifer,Whalen,JWHALEN,515.123.4444,17-SEP-03,AD_ASST,-0.388628,-,101,10
3,201,Michael,Hartstein,MHARTSTE,515.123.5555,17-FEB-04,MK_MAN,1.486570,-,100,20
4,202,Pat,Fay,PFAY,603.123.6666,17-AUG-05,MK_REP,-0.039754,-,201,20
5,203,Susan,Mavris,SMAVRIS,515.123.7777,07-JUN-02,HR_REP,0.069269,-,101,40
6,204,Hermann,Baer,HBAER,515.123.8888,07-JUN-02,PR_REP,0.832431,-,101,70
7,205,Shelley,Higgins,SHIGGINS,515.123.8080,07-JUN-02,AC_MGR,1.270268,-,101,110
8,206,William,Gietz,WGIETZ,515.123.8181,07-JUN-02,AC_ACCOUNT,0.461752,-,205,110
9,100,Steven,King,SKING,515.123.4567,17-JUN-03,AD_PRES,3.885079,-,-,90
10,101,Neena,Kochhar,NKOCHHAR,515.123.4568,21-SEP-05,AD_VP,2.358755,-,100,90
11,102,Lex,De Haan,LDEHAAN,515.123.4569,13-JAN-01,AD_VP,2.358755,-,100,90
12,103,Alexander,Hunold,AHUNOLD,590.423.4567,03-JAN-06,IT_PROG,0.614385,-,102,60
13,104,Bruce,Ernst,BERNST,590.423.4568,21-MAY-07,IT_PROG,-0.039754,-,103,60
14,105,David,Austin,DAUSTIN,590.423.4569,25-JUN-05,IT_PROG,-0.301410,-,103,60
15,106,Valli,Pataballa,VPATABAL,590.423.4560,05-FEB-06,IT_PROG,-0.301410,-,103,60
16,107,Diana,Lorentz,DLORENTZ,590.423.5567,07-FEB-07,IT_PROG,-0.432238,-,103,60
17,108,Nancy,Greenberg,NGREENBE,515.124.4569,17-AUG-02,FI_MGR,1.270268,-,101,100
18,109,Daniel,Faviet,DFAVIET,515.124.4169,16-AUG-02,FI_ACCOUNT,0.614385,-,108,100
19,110,John,Chen,JCHEN,515.124.4269,28-SEP-05,FI_ACCOUNT,0.439948,-,108,100
20,111,Ismael,Sciarra,ISCIARRA,515.124.4369,30-SEP-05,FI_ACCOUNT,0.330925,-,108,100
21,112,Jose Manuel,Urman,JMURMAN,515.124.4469,07-MAR-06,FI_ACCOUNT,0.352729,-,108,100
22,113,Luis,Popp,LPOPP,515.124.4567,07-DEC-07,FI_ACCOUNT,0.156487,-,108,100
23,114,Den,Raphaely,DRAPHEAL,515.127.4561,07-DEC-02,PU_MAN,1.050477,-,100,30
24,115,Alexander,Khoo,AKHOO,515.127.4562,18-MAY-03,PU_CLERK,-0.672088,-,114,30
25,116,Shelli,Baida,SBAIDA,515.127.4563,24-DEC-05,PU_CLERK,-0.715698,-,114,30
26,117,Sigal,Tobias,STOBIAS,515.127.4564,24-JUL-05,PU_CLERK,-0.737502,-,114,30
27,118,Guy,Himuro,GHIMURO,515.127.4565,15-NOV-06,PU_CLERK,-0.781112,-,114,30
28,119,Karen,Colmenares,KCOLMENA,515.127.4566,10-AUG-07,PU_CLERK,-0.802916,-,114,30
29,120,Matthew,Weiss,MWEISS,650.123.1234,18-JUL-04,ST_MAN,0.396338,-,100,50
30,121,Adam,Fripp,AFRIPP,650.123.2234,10-APR-05,ST_MAN,0.439948,-,100,50
31,122,Payam,Kaufling,PKAUFLIN,650.123.3234,01-MAY-03,ST_MAN,0.374534,-,100,50
32,123,Shanta,Vollman,SVOLLMAN,650.123.4234,10-OCT-05,ST_MAN,0.069269,-,100,50
33,124,Kevin,Mourgos,KMOURGOS,650.123.5234,16-NOV-07,ST_MAN,-0.083363,-,100,50
34,125,Julia,Nayer,JNAYER,650.124.1214,16-JUL-05,ST_CLERK,-0.650284,-,120,50
35,126,Irene,Mikkilineni,IMIKKILI,650.124.1224,28-SEP-06,ST_CLERK,-0.759307,-,120,50
36,127,James,Landry,JLANDRY,650.124.1334,14-JAN-07,ST_CLERK,-0.824721,-,120,50
37,128,Steven,Markle,SMARKLE,650.124.1434,08-MAR-08,ST_CLERK,-0.868330,-,120,50
38,129,Laura,Bissot,LBISSOT,650.124.5234,20-AUG-05,ST_CLERK,-0.628479,-,121,50
39,130,Mozhe,Atkinson,MATKINSO,650.124.6234,30-OCT-05,ST_CLERK,-0.737502,-,121,50
40,131,James,Marlow,JAMRLOW,650.124.7234,16-FEB-05,ST_CLERK,-0.802916,-,121,50
41,132,TJ,Olson,TJOLSON,650.124.8234,10-APR-07,ST_CLERK,-0.890135,-,121,50
42,133,Jason,Mallin,JMALLIN,650.127.1934,14-JUN-04,ST_CLERK,-0.628479,-,122,50
43,134,Michael,Rogers,MROGERS,650.127.1834,26-AUG-06,ST_CLERK,-0.715698,-,122,50
44,135,Ki,Gee,KGEE,650.127.1734,12-DEC-07,ST_CLERK,-0.824721,-,122,50
45,136,Hazel,Philtanker,HPHILTAN,650.127.1634,06-FEB-08,ST_CLERK,-0.868330,-,122,50
46,137,Renske,Ladwig,RLADWIG,650.121.1234,14-JUL-03,ST_CLERK,-0.563065,-,123,50
47,138,Stephen,Stiles,SSTILES,650.121.2034,26-OCT-05,ST_CLERK,-0.650284,-,123,50
48,139,John,Seo,JSEO,650.121.2019,12-FEB-06,ST_CLERK,-0.759307,-,123,50
49,140,Joshua,Patel,JPATEL,650.121.1834,06-APR-06,ST_CLERK,-0.802916,-,123,50

In [16]:
import math
j=math.ceil(math.log(salary.max(),10))

5